name: gredu_unleash
description: A simple tools for feature toggle. This is a simple helper for using Unleash Feature Flag
version: 0.0.1
homepage: https://github.com/greduasia/gredu_unleash
repository: https://github.com/greduasia/gredu_unleash
issue_tracker: https://github.com/greduasia/gredu_unleash/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.13.4
  lints: ^1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
